version: "3.9"

services:
  serpbear:
    image: towfiqi/serpbear:latest
    container_name: serpbear
    hostname: serpbear
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
    user: 1026:100
    ports:
      - 8495:3000
    volumes:
      - /volume1/docker/serpbear:/app/data
    restart: always
