global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

# (Optional) Log information
# ---
# log:
#  level: ERROR  # DEBUG, INFO, WARNING, ERROR, CRITICAL
#   format: common  # common, json, logfmt
#   filePath: /var/log/traefik/traefik.log

# (Optional) Accesslog
# ---
# accesslog:
  # format: common  # common, json, logfmt
  # filePath: /var/log/traefik/access.log

# (Optional) Enable API and Dashboard
# ---
# api:
#  dashboard: true  # true by default
#  insecure: true  # Don't do this in production!
api:
  dashboard: true
  debug: true

# Entry Points configuration
# ---
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  https:
    address: ":443"

providers:
  docker:
    exposedByDefault: false # Default is true
  file:
    filename: config.yml
    watch: true

# Configure your CertificateResolver here...
# ---
certificatesResolvers:
  cloudflare:
    acme:
      email: thedaviddias@gmail.com
      storage: acme.json
      #disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
