version: "3"

services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /volume1/docker/homer:/www/assets
    ports:
      - 8092:8080
    user: 1026:100
    environment:
      - INIT_ASSETS=0
    restart: unless-stopped
